#!/bin/bash

mapfile -t VMARRAY < <(virsh list --all | awk 'NR > 2 && NF > 1 {print $2}');

declare -i X;
declare PATH="${VMPATH}/backup/XML"

for VM in "${VMARRAY[@]}"
do

    # create backup file
    /bin/virsh dumpxml "${VM}" > "${PATH}/${VM}.xml.$(/sbin/date +%F)";

    # cleanup backup files if more than 3

    mapfile -t BACKUPS < <(/sbin/ls -lrat "${PATH}/${VM}.xml"* | /sbin/awk '{print $9}');
    X="${#BACKUPS[@]}";

    if [[ "${X}" -ge 4 ]]; then
        until [ "${X}" -eq 3 ];
        do
            /sbin/rm "${BACKUPS[("${X}" - "${#BACKUPS[@]}") * -1]}";
            X=X-1;
        done
    fi
done;

